/* eslint-disable @typescript-eslint/no-explicit-any */
import React from "react";
import { useLoaderData } from "react-router";

type SaleProduct = {
    product: {
        name: string;
    };
    qty: number;
    unitPrice: number;
    total: number;
};

export type Sale = {
    items: any;
    _id: string;
    customer: {
        name: string;
        phone: string;
    };
    phone: string;
    invoice: string;
    date: string;
    address?: string;
    salesProducts: SaleProduct[];
    subTotal: number;
    discount?: number;
    grandTotal: number;
    paidAmount?: number;
    dueAmount?: number;
    status: string;
};

const PrintableInvoice: React.FC = () => {


    const { data } = useLoaderData() as { data: Sale };

    const onClose = () => {
        window.close();
    };

    return (
        <div className="fixed inset-0 bg-black/40 flex justify-center items-center p-4 z-50 print:bg-white print:p-0">
            <div className="bg-white w-[800px] p-8 shadow-xl rounded print:shadow-none print:w-full print:h-full">

                {/* HEADER */}
                <div className="text-center mb-6 border-b pb-4">
                    <h2 className="text-2xl font-bold">মেসার্স এম আই ট্রেডিং</h2>
                    <p className="text-sm">সকল প্রকার ডাল, বুট, মসলার পাইকারি ও কমিশন সেলের আড়ৎ  </p>
                    <p className="text-xs mt-1 text-gray-600">Phone:  01842753607  mitrading.202ktg@gmail.com</p>
                </div>

                {/* CUSTOMER INFO */}
                <div className="flex justify-between text-sm mb-6">
                    <div>
                        <p><strong>Customer:</strong> {data?.customer.name}</p>
                        <p><strong>Phone:</strong> {data?.customer.phone}</p>
                        {data?.address && <p><strong>Address:</strong> {data?.address}</p>}
                    </div>
                    <div className="text-right">
                        <p><strong>Invoice ID:</strong> {data?.invoice}</p>
                        <p><strong>Date:</strong> {new Date(data?.date).toLocaleDateString()}</p>
                    </div>
                </div>

                {/* PRODUCT TABLE */}
                <table className="w-full border-collapse text-sm">
                    <thead>
                        <tr className="bg-gray-100 border">
                            <th className="border p-2 text-left">Product</th>
                            <th className="border p-2 text-center">Qty</th>
                            <th className="border p-2 text-right">Price</th>
                            <th className="border p-2 text-right">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {data?.salesProducts?.map((item, idx) => (
                            <tr key={idx} className="border">
                                <td className="border p-2">{item?.product?.name}</td>
                                <td className="border p-2 text-center">{item?.qty}</td>
                                <td className="border p-2 text-right">{item?.unitPrice}</td>
                                <td className="border p-2 text-right font-semibold">{item?.total}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>

                {/* SUMMARY */}
                <div className="flex justify-end mt-6">
                    <div className="w-64 text-sm">
                        <div className="flex justify-between py-1">
                            <span>Subtotal</span>
                            <span>{data?.subTotal}</span>
                        </div>
                        <div className="flex justify-between py-1">
                            <span>Discount</span>
                            <span>{data?.discount || 0}</span>
                        </div>
                        <div className="flex justify-between py-1 font-semibold">
                            <span>Grand Total</span>
                            <span>{data?.grandTotal}</span>
                        </div>
                        <div className="flex justify-between py-1">
                            <span>Paid</span>
                            <span>{data?.paidAmount || 0}</span>
                        </div>
                        <div className="flex justify-between py-1">
                            <span>Due</span>
                            <span>{data?.dueAmount || 0}</span>
                        </div>
                    </div>
                </div>

                {/* FOOTER */}
                <div className="flex justify-between items-center mt-10 print:hidden">
                    <div className="text-xs text-gray-600">Generated by Hydro Tech</div>
                    <div className="flex gap-2">
                        <button
                            className="px-4 py-2 border rounded hover:bg-gray-100"
                            onClick={() => window.print()}
                        >
                            Print
                        </button>
                        <button
                            className="px-4 py-2 bg-red-100 text-red-700 rounded"
                            onClick={onClose}
                        >
                            Close
                        </button>
                    </div>
                </div>

            </div>
        </div>
    );
};

export default PrintableInvoice;
