/* eslint-disable @typescript-eslint/no-explicit-any */
import React, { useState } from 'react';
import { useGetAllSalesQuery } from '../../redux/features/sales/salesApi';
import type { Sale } from '../../components/table/PrintableInvoice';
import TableSkeleton from '../../components/table/TableSkeleton';
import ErrorBoundary from '../../components/ErrorBoundary';
import { salesTableHeads } from './salesTableHeads';
import SalesTableBody from './SalesTableBody';
import { SalesDeliveryModal } from './SalesDeliveryModal';

const PrintableInvoice: React.FC<{ sale: Sale | null; onClose: () => void }> = ({ sale, onClose }) => {
    if (!sale) return null;

    return (
        <div className="fixed inset-0 z-50 flex items-start justify-center p-6 bg-black/40">

            <div className="bg-white w-full max-w-3xl rounded shadow-lg overflow-auto print-area">
                <div>
                    <div className="text-center  border-b pb-4">
                        <h2 className="text-2xl font-bold">মেসার্স এম আই ট্রেডিং</h2>
                        <p className="text-sm">সকল প্রকার ডাল, বুট, মসলার পাইকারি ও কমিশন সেলের আড়ৎ  </p>
                        <p className="text-xs mt-1 text-gray-600">Phone:  01842753607  mitrading.202ktg@gmail.com</p>
                    </div>
                </div>
                <div className="p-6 print:p-0 ">

                    <div className="flex justify-between items-start">

                        <div>
                            <h2 className="text-2xl font-bold">Invoice</h2>
                            <p className="text-sm text-gray-600">Invoice #: {sale.invoice}</p>
                            <p className="text-sm text-gray-600">Date: {new Date(sale.date).toLocaleString()}</p>
                        </div>
                        <div className="text-right">
                            <p className="font-semibold">{sale.customer.name}</p>
                            <p className="text-sm text-gray-600">{sale.customer.phone}</p>
                        </div>
                    </div>

                    <hr className="my-4" />

                    <table className="w-full text-sm">
                        <thead>
                            <tr className="text-left">
                                <th className="pb-2">#</th>
                                <th className="pb-2">Product</th>
                                <th className="pb-2">Qty</th>
                                <th className="pb-2">Unit</th>
                                <th className="pb-2 text-right">Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            {sale.salesProducts?.map((p, idx) => (
                                <tr key={idx} className="border-t">
                                    <td className="py-2">{idx + 1}</td>
                                    <td className="py-2">{typeof p.product === 'string' ? p.product : (p.product as any)?.name || (p.product as any)?._id}</td>
                                    <td className="py-2">{p.qty}</td>
                                    <td className="py-2">{p.unitPrice}</td>
                                    <td className="py-2 text-right">{p.total}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>

                    <div className="mt-4 flex justify-end gap-6">
                        <div className="w-60">
                            <div className="flex justify-between py-1"><span>Subtotal</span><span>{sale.subTotal}</span></div>
                            <div className="flex justify-between py-1"><span>Discount</span><span>{sale.discount || 0}</span></div>
                            <div className="flex justify-between py-1 font-semibold"><span>Grand Total</span><span>{sale.grandTotal}</span></div>
                            <div className="flex justify-between py-1"><span>Paid</span><span>{sale.paidAmount || 0}</span></div>
                            <div className="flex justify-between py-1"><span>Due</span><span>{sale.dueAmount || 0}</span></div>
                        </div>
                    </div>

                    <div className="flex justify-between items-center mt-8 pb-6">
                        <div className="text-xs text-gray-600">Generated by Hydro Tech</div>
                        <div className="flex gap-2">
                            <button
                                className="px-4 py-2 border rounded hover:bg-gray-50"
                                onClick={() => window.print()}
                            >
                                Print
                            </button>
                            <button
                                className="px-4 py-2 bg-red-50 text-red-700 rounded"
                                onClick={onClose}
                            >
                                Close
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};


/* ---------------------------------------------
   Main Component
   ---------------------------------------------*/

const SalesOverviewWithInvoice: React.FC = () => {
    const [page, setPage] = useState<number>(1);
    const [limit, setLimit] = useState<number>(10);
    const [search, setSearch] = useState<string>('');
    const [sortBy, setSortBy] = useState<string>('createdAt');
    const [order, setOrder] = useState('asc');
    const [paymentMethod, setPaymentMethod] = useState<string>('');
    const [broker, setBroker] = useState<string>('');
    const [dateFrom, setDateFrom] = useState<string>('');
    const [dateTo, setDateTo] = useState<string>('');

    const [expandedRows, setExpandedRows] = useState<Record<string, boolean>>({});
    const [selectedSale, setSelectedSale] = useState<Sale | null>(null);
    const [delivery, setDelivery] = useState<{ items: any[] } | null>(null);

    // call user's hook
    const { data, isLoading, isError, error } = useGetAllSalesQuery({ page, limit, search, order, sortBy, dateFrom, dateTo, paymentMethod, broker });

    const sales = data?.data.data || [];
    const total = data?.total || 0;
    const totalPages = Math.max(1, Math.ceil(total / limit));

    const toggleExpand = (id: string) => {
        setExpandedRows((prev) => ({ ...prev, [id]: !prev[id] }));
    };

    const openInvoice = (sale: Sale) => setSelectedSale(sale);
    const closeInvoice = () => setSelectedSale(null);
    const deliveryModalClose = () => setDelivery(null);

    const onSearchSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        setPage(1);
    };

    const clearFilters = () => {
        setSearch('');
        setBroker('');
        setPaymentMethod('');
        setDateFrom('');
        setDateTo('');
        setPage(1);
    };

    if (isError) {
        return <ErrorBoundary />
    }
    return (
        <div className="p-4 space-y-4">
            {/* Filters and search */}
            <form onSubmit={onSearchSubmit} className="flex flex-wrap gap-3 items-center justify-between">
                <div className="flex gap-2 flex-wrap items-center">
                    <input
                        value={search}
                        onChange={(e) => setSearch(e.target.value)}
                        placeholder="Search customer, invoice or phone..."
                        className="border rounded px-3 py-2 text-sm w-64"
                    />

                    <select value={paymentMethod} onChange={(e) => setPaymentMethod(e.target.value)} className="border rounded px-3 py-2 text-sm">
                        <option value="">All payment</option>
                        <option value="cash">Cash</option>
                        <option value="bank">Bank</option>
                        <option value="mobile">Mobile</option>
                    </select>

                    <input type="date" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} className="border rounded px-3 py-2 text-sm" />
                    <input type="date" value={dateTo} onChange={(e) => setDateTo(e.target.value)} className="border rounded px-3 py-2 text-sm" />

                    <input value={broker} onChange={(e) => setBroker(e.target.value)} placeholder="Broker" className="border rounded px-3 py-2 text-sm" />

                    <button type="submit" className="px-3 py-2 bg-blue-600 text-white rounded text-sm">Search</button>
                    <button type="button" onClick={clearFilters} className="px-3 py-2 border rounded text-sm">Clear</button>
                </div>

                <div className="flex gap-2 items-center">
                    <label className="text-sm">Sort:</label>
                    <button
                        type="button"
                        onClick={() => setOrder(order === 'asc' ? 'desc' : 'asc')}
                        className="px-3 py-2 border rounded text-sm"
                    >
                        {order === 'asc' ? 'Ascending' : 'Descending'}
                    </button>

                    <label className="text-sm">Sort:</label>
                    <select value={sortBy} onChange={(e) => { setSortBy(e.target.value) }} className="border rounded px-3 py-2 text-sm">
                        <option value='createdAt'>Date</option>
                        <option value='grandTotal'>Grand Total</option>
                        <option value='customer'>Customer</option>
                    </select>
                    <select value={limit} onChange={(e) => { setLimit(Number(e.target.value)); setPage(1); }} className="border rounded px-3 py-2 text-sm">
                        <option value={5}>5</option>
                        <option value={10}>10</option>
                        <option value={25}>25</option>
                        <option value={50}>50</option>
                        <option value={100}>100</option>
                    </select>
                </div>
            </form>

            {/* Table container */}
            <div className="overflow-x-auto bg-white rounded-lg shadow-sm">
                {isLoading ? (
                    <TableSkeleton row={10} />
                ) : isError ? (
                    <div className="p-4 text-red-600">{(error as any)?.data?.message || 'Error loading sales'}</div>
                ) : sales?.length === 0 ? (
                    <p className="text-center text-gray-500 py-4">No sales found.</p>
                ) : (
                    <table className="min-w-full bg-white text-sm">
                        <thead className="bg-gray-100 text-gray-700 text-left">
                            <tr>
                                {
                                    salesTableHeads?.map((head: any, idx) => (
                                        <th key={idx} className="px-4 py-2 border-b">{head}</th>
                                    ))
                                }
                            </tr>
                        </thead>
                        <tbody>
                            {sales?.map((row: Sale, idx: number) => (
                                <SalesTableBody
                                    key={row._id}
                                    row={row}
                                    page={page}
                                    limit={limit}
                                    idx={idx}
                                    toggleExpand={toggleExpand}
                                    expandedRows={expandedRows}
                                    openInvoice={openInvoice}
                                    setDelivery={setDelivery}
                                />
                            ))}
                        </tbody>
                    </table>
                )}
            </div>

            {/* Pagination */}
            <div className="flex items-center justify-between mt-4">
                <div className="text-sm text-gray-600">Page {page} of {totalPages}</div>
                <div className="flex gap-2">
                    <button disabled={page === 1} onClick={() => setPage((p) => Math.max(1, p - 1))} className="px-3 py-2 border rounded disabled:opacity-50">Prev</button>
                    <button disabled={page === totalPages} onClick={() => setPage((p) => Math.min(totalPages, p + 1))} className="px-3 py-2 border rounded disabled:opacity-50">Next</button>
                </div>
            </div>

            {/* Invoice modal / print area */}
            {selectedSale && <PrintableInvoice sale={selectedSale} onClose={closeInvoice} />}

            <SalesDeliveryModal item={delivery} deliveryModalClose={deliveryModalClose} />
            {/* small explanatory footer */}
            <div className="text-xs text-gray-500">Tip: Use server-side query params for fast pagination and index the fields used for filtering (salesDate, invoice, customer, paymentMethod).</div>
        </div>
    );
};

export default SalesOverviewWithInvoice;
